service: simotec-sls
frameworkVersion: "3"

custom:
  customDomain:
    domainName: ${env:AWS_DOMAIN_NAME}
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional
    certificateArn: ${env:AWS_CERTIFICATE_ARN}

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage}
  region: us-east-1
  tags:
    CLIENT: simotec
    STAGE: ${self:provider.stage}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
  environment:
    TZ: America/Santiago
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    DB_SSL_CA: ${env:DB_SSL_CA}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    CORS_ORIGIN: ${env:CORS_ORIGIN}

functions: ${file(./resources/functions.yml):functions}
