provider:
  name: aws
  runtime: nodejs20.x
  timeout: 20
  memorySize: 3000 
  # stage: ${opt:stage, 'dev'}  # Comentado o puedes dejar stage: ""
  stage: ""
  region: us-east-2
  tags:
    CLIENT: simotec
    STAGE: ${self:provider.stage}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
  environment:
    TZ: America/Santiago
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    CORS_ORIGIN: ${env:CORS_ORIGIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rds:DescribeDBInstances"
        - "rds:Connect"
      Resource: "*"
functions: ${file(./resources/functions.yml):functions}
